CREATE TABLE usuarios(
 id BIGINT NOT NULL AUTO_INCREMENT,
 nombre VARCHAR(100) NOT NULL,
 correo_electronico VARCHAR(100) NOT NULL,
 contrasenia VARCHAR(100) NOT NULL,
 perfil_id INTEGER NOT NULL,
 PRIMARY KEY(id)
);