CREATE TABLE respuestas(
 id INTEGER NOT NULL AUTO_INCREMENT,
 mensaje VARCHAR(200) NOT NULL,
 solucion VARCHAR(200) NOT NULL,
 fecha_creacion DATETIME NOT NULL,
 usuario_id BIGINT NOT NULL,
 topico_id BIGINT NOT NULL,
 PRIMARY KEY(id)
);